### ISSUE TITLE
Random game

### ISSUE THREAD

**Issue by aleff-github** [mazurpator/FreecellJLabel#1]
Why did you use seed in Deck.java?
`public Deck(long seed)  {
        random = new Random(seed);
        System.out.println(random.toString());
        // char[ ] suite = {'C', 'D', 'H', 'S'}; // clubs .. spades
        for (int s = 0; s < 4; s++) {
            for (int r = 1; r < 14; r++) { // ace 2 .. king
                deck[count] = new Card(r, s);
                count++;
            }//for
        }//for
    }//constructor`
    
If you remove `seed` it works correctly, else, you will have the same cards ever

**Comment by bronzodile** [comment]
I used a hardcoded seed value of 6 because it gave me a nice repeatable deck every time I run the program during testing and debugging. Once the development is over, it is not needed anymore. The latest commit has an updated version with no fixed seed.
